// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SincoWebApi.Infrastructure.Persistence;

#nullable disable

namespace SincoWebApi.Infrastructure.Migrations
{
    [DbContext(typeof(SincoDbContext))]
    [Migration("20260301165442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SincoWebApi.Domain.Entities.EstadoPaquete", b =>
                {
                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("EstadoId");

                    b.ToTable("tblEstadoPaquete", (string)null);

                    b.HasData(
                        new
                        {
                            EstadoId = 1,
                            Descripcion = "En bodega"
                        },
                        new
                        {
                            EstadoId = 2,
                            Descripcion = "Asignado"
                        },
                        new
                        {
                            EstadoId = 3,
                            Descripcion = "Entregado"
                        });
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.Paquete", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteId"));

                    b.Property<string>("CodigoSeguimiento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.HasKey("PaqueteId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PrioridadId");

                    b.ToTable("tblPaquete", (string)null);
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.PaqueteRepartidor", b =>
                {
                    b.Property<int>("PaqueteRepartidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteRepartidorId"));

                    b.Property<int>("PaqueteId")
                        .HasColumnType("int");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("int");

                    b.HasKey("PaqueteRepartidorId");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("RepartidorId");

                    b.ToTable("PaqueteRepartidor", (string)null);
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.Prioridad", b =>
                {
                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("PrioridadId");

                    b.ToTable("tblPrioridad", (string)null);

                    b.HasData(
                        new
                        {
                            PrioridadId = 1,
                            Descripcion = "Alta"
                        },
                        new
                        {
                            PrioridadId = 2,
                            Descripcion = "Media"
                        },
                        new
                        {
                            PrioridadId = 3,
                            Descripcion = "Baja"
                        });
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.Repartidor", b =>
                {
                    b.Property<int>("RepartidorId")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("RepartidorId");

                    b.ToTable("tblRepartidor", (string)null);

                    b.HasData(
                        new
                        {
                            RepartidorId = 1,
                            Apellido = "Monsalve",
                            Nombre = "Andres"
                        },
                        new
                        {
                            RepartidorId = 2,
                            Apellido = "Chavez",
                            Nombre = "Juan"
                        },
                        new
                        {
                            RepartidorId = 3,
                            Apellido = "Ortiz",
                            Nombre = "Esteban"
                        },
                        new
                        {
                            RepartidorId = 4,
                            Apellido = "Quiñones",
                            Nombre = "Andres"
                        },
                        new
                        {
                            RepartidorId = 5,
                            Apellido = "Quiroga",
                            Nombre = "Laura"
                        });
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.Paquete", b =>
                {
                    b.HasOne("SincoWebApi.Domain.Entities.EstadoPaquete", "EstadoPaquete")
                        .WithMany("Paquetes")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SincoWebApi.Domain.Entities.Prioridad", "Prioridad")
                        .WithMany("Paquetes")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPaquete");

                    b.Navigation("Prioridad");
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.PaqueteRepartidor", b =>
                {
                    b.HasOne("SincoWebApi.Domain.Entities.Paquete", "Paquete")
                        .WithMany("PaqueteRepartidores")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SincoWebApi.Domain.Entities.Repartidor", "Repartidor")
                        .WithMany("PaqueteRepartidores")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paquete");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.EstadoPaquete", b =>
                {
                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.Paquete", b =>
                {
                    b.Navigation("PaqueteRepartidores");
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.Prioridad", b =>
                {
                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("SincoWebApi.Domain.Entities.Repartidor", b =>
                {
                    b.Navigation("PaqueteRepartidores");
                });
#pragma warning restore 612, 618
        }
    }
}
